export const RouteEnum = {
  HOME: "/",
  // DASHBOARD: "/",
  LOGIN: "/login",
  SCHOLARSHIPS: "/scholarships",
  INVEST: "/invest",
  SIGNUP: "/signup",
  DASHBOARD: "/dashboard",
  CONTRIBUTION: "/contribution",

  GRANT: "/grant",
  PROFILE: "/profile",
  LOAN: "/loan",
  VERIFYACCOUNT: "/verify-account",
  MANAGE_COMPANIES: "/m",
  MANAGE_RIDERS: "/m",
  TRIPS: "/m",
  MAPS: "/m",
  SUPPORT: "/m",
};
