export const RouteEnum = {
  HOME: "/",
  // DASHBOARD: "/",
  LOGIN: "/login",
  SCHOLARSHIPS: "/scholarships",
  INVEST: "/invest",
  SIGNUP: "/signup",
  DASHBOARD: "/dashboard",
  CONTRIBUTION: "/contribution",
  LANDING: "/",
  WHATWEDO: "/what-we-do",
  OURVALUES: "/our-values",
  TEAM: "/team",
  STORY: "/about",
  HOWITWORKS: "/how-it-works",

  GRANT: "/grant",
  PROFILE: "/profile",
  LOAN: "/loan",
  VERIFYACCOUNT: "/verify-account",
  ABOUT: "/about",
};
